// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tenant

import (
	"github.com/gin-gonic/gin"
	"saas/internal/tenant/adapters"
	"saas/internal/tenant/handler"
	"saas/internal/tenant/service"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	tenantRepository := adapters.NewTenantPSQLRepository()
	tenantCache := adapters.NewTenantRedisCache()
	tenantService := service.NewTenantService(tenantRepository, tenantCache)
	httpHandler := handler.NewHttpHandler(tenantService)
	v := RegisterV1(r, httpHandler)
	return v
}
