// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role


import (
	"github.com/gin-gonic/gin"
	"saas/internal/role/adapters"
	"saas/internal/role/handler"
	"saas/internal/role/service"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	roleRepository := adapters.NewPSQLRoleRepository()
	roleService := service.NewRoleService(roleRepository)
	httpHandler := handler.NewHttpHandler(roleService)
	v := RegisterV1(r, httpHandler)
	return v
}
