// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package plan


import (
	"github.com/gin-gonic/gin"
	"saas/internal/plan/adapters"
	"saas/internal/plan/handler"
	"saas/internal/plan/service"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	planRepository := adapters.NewPlanPSQLRepository()
	planService := service.NewPlanService(planRepository)
	httpHandler := handler.NewHttpHandler(planService)
	v := RegisterV1(r, httpHandler)
	return v
}
