// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Apis           string
	Buttons        string
	CasbinRule     string
	ImgCategories  string
	Imgs           string
	Menus          string
	Mock           string
	Plans          string
	RoleButton     string
	RoleMenu       string
	Roles          string
	TenantPlan     string
	TenantUserRole string
	Tenants        string
	Users          string
}{
	Apis:           "apis",
	Buttons:        "buttons",
	CasbinRule:     "casbin_rule",
	ImgCategories:  "img_categories",
	Imgs:           "imgs",
	Menus:          "menus",
	Mock:           "mock",
	Plans:          "plans",
	RoleButton:     "role_button",
	RoleMenu:       "role_menu",
	Roles:          "roles",
	TenantPlan:     "tenant_plan",
	TenantUserRole: "tenant_user_role",
	Tenants:        "tenants",
	Users:          "users",
}
