// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CommentTenantConfig is an object representing the database table.
type CommentTenantConfig struct {
	TenantID  string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	IfAudit   bool      `boil:"if_audit" json:"if_audit" toml:"if_audit" yaml:"if_audit"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *commentTenantConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L commentTenantConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CommentTenantConfigColumns = struct {
	TenantID  string
	IfAudit   string
	CreatedAt string
	UpdatedAt string
}{
	TenantID:  "tenant_id",
	IfAudit:   "if_audit",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var CommentTenantConfigTableColumns = struct {
	TenantID  string
	IfAudit   string
	CreatedAt string
	UpdatedAt string
}{
	TenantID:  "comment_tenant_configs.tenant_id",
	IfAudit:   "comment_tenant_configs.if_audit",
	CreatedAt: "comment_tenant_configs.created_at",
	UpdatedAt: "comment_tenant_configs.updated_at",
}

// Generated where

var CommentTenantConfigWhere = struct {
	TenantID  whereHelperstring
	IfAudit   whereHelperbool
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	TenantID:  whereHelperstring{field: "\"comment_tenant_configs\".\"tenant_id\""},
	IfAudit:   whereHelperbool{field: "\"comment_tenant_configs\".\"if_audit\""},
	CreatedAt: whereHelpertime_Time{field: "\"comment_tenant_configs\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"comment_tenant_configs\".\"updated_at\""},
}

// CommentTenantConfigRels is where relationship names are stored.
var CommentTenantConfigRels = struct {
	Tenant string
}{
	Tenant: "Tenant",
}

// commentTenantConfigR is where relationships are stored.
type commentTenantConfigR struct {
	Tenant *Tenant `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
}

// NewStruct creates a new relationship struct
func (*commentTenantConfigR) NewStruct() *commentTenantConfigR {
	return &commentTenantConfigR{}
}

func (o *CommentTenantConfig) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *commentTenantConfigR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

// commentTenantConfigL is where Load methods for each relationship are stored.
type commentTenantConfigL struct{}

var (
	commentTenantConfigAllColumns            = []string{"tenant_id", "if_audit", "created_at", "updated_at"}
	commentTenantConfigColumnsWithoutDefault = []string{"tenant_id"}
	commentTenantConfigColumnsWithDefault    = []string{"if_audit", "created_at", "updated_at"}
	commentTenantConfigPrimaryKeyColumns     = []string{"tenant_id"}
	commentTenantConfigGeneratedColumns      = []string{}
)

type (
	// CommentTenantConfigSlice is an alias for a slice of pointers to CommentTenantConfig.
	// This should almost always be used instead of []CommentTenantConfig.
	CommentTenantConfigSlice []*CommentTenantConfig
	// CommentTenantConfigHook is the signature for custom CommentTenantConfig hook methods
	CommentTenantConfigHook func(boil.Executor, *CommentTenantConfig) error

	commentTenantConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	commentTenantConfigType                 = reflect.TypeOf(&CommentTenantConfig{})
	commentTenantConfigMapping              = queries.MakeStructMapping(commentTenantConfigType)
	commentTenantConfigPrimaryKeyMapping, _ = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, commentTenantConfigPrimaryKeyColumns)
	commentTenantConfigInsertCacheMut       sync.RWMutex
	commentTenantConfigInsertCache          = make(map[string]insertCache)
	commentTenantConfigUpdateCacheMut       sync.RWMutex
	commentTenantConfigUpdateCache          = make(map[string]updateCache)
	commentTenantConfigUpsertCacheMut       sync.RWMutex
	commentTenantConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var commentTenantConfigAfterSelectMu sync.Mutex
var commentTenantConfigAfterSelectHooks []CommentTenantConfigHook

var commentTenantConfigBeforeInsertMu sync.Mutex
var commentTenantConfigBeforeInsertHooks []CommentTenantConfigHook
var commentTenantConfigAfterInsertMu sync.Mutex
var commentTenantConfigAfterInsertHooks []CommentTenantConfigHook

var commentTenantConfigBeforeUpdateMu sync.Mutex
var commentTenantConfigBeforeUpdateHooks []CommentTenantConfigHook
var commentTenantConfigAfterUpdateMu sync.Mutex
var commentTenantConfigAfterUpdateHooks []CommentTenantConfigHook

var commentTenantConfigBeforeDeleteMu sync.Mutex
var commentTenantConfigBeforeDeleteHooks []CommentTenantConfigHook
var commentTenantConfigAfterDeleteMu sync.Mutex
var commentTenantConfigAfterDeleteHooks []CommentTenantConfigHook

var commentTenantConfigBeforeUpsertMu sync.Mutex
var commentTenantConfigBeforeUpsertHooks []CommentTenantConfigHook
var commentTenantConfigAfterUpsertMu sync.Mutex
var commentTenantConfigAfterUpsertHooks []CommentTenantConfigHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CommentTenantConfig) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CommentTenantConfig) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CommentTenantConfig) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CommentTenantConfig) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CommentTenantConfig) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CommentTenantConfig) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CommentTenantConfig) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CommentTenantConfig) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CommentTenantConfig) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range commentTenantConfigAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCommentTenantConfigHook registers your hook function for all future operations.
func AddCommentTenantConfigHook(hookPoint boil.HookPoint, commentTenantConfigHook CommentTenantConfigHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		commentTenantConfigAfterSelectMu.Lock()
		commentTenantConfigAfterSelectHooks = append(commentTenantConfigAfterSelectHooks, commentTenantConfigHook)
		commentTenantConfigAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		commentTenantConfigBeforeInsertMu.Lock()
		commentTenantConfigBeforeInsertHooks = append(commentTenantConfigBeforeInsertHooks, commentTenantConfigHook)
		commentTenantConfigBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		commentTenantConfigAfterInsertMu.Lock()
		commentTenantConfigAfterInsertHooks = append(commentTenantConfigAfterInsertHooks, commentTenantConfigHook)
		commentTenantConfigAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		commentTenantConfigBeforeUpdateMu.Lock()
		commentTenantConfigBeforeUpdateHooks = append(commentTenantConfigBeforeUpdateHooks, commentTenantConfigHook)
		commentTenantConfigBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		commentTenantConfigAfterUpdateMu.Lock()
		commentTenantConfigAfterUpdateHooks = append(commentTenantConfigAfterUpdateHooks, commentTenantConfigHook)
		commentTenantConfigAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		commentTenantConfigBeforeDeleteMu.Lock()
		commentTenantConfigBeforeDeleteHooks = append(commentTenantConfigBeforeDeleteHooks, commentTenantConfigHook)
		commentTenantConfigBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		commentTenantConfigAfterDeleteMu.Lock()
		commentTenantConfigAfterDeleteHooks = append(commentTenantConfigAfterDeleteHooks, commentTenantConfigHook)
		commentTenantConfigAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		commentTenantConfigBeforeUpsertMu.Lock()
		commentTenantConfigBeforeUpsertHooks = append(commentTenantConfigBeforeUpsertHooks, commentTenantConfigHook)
		commentTenantConfigBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		commentTenantConfigAfterUpsertMu.Lock()
		commentTenantConfigAfterUpsertHooks = append(commentTenantConfigAfterUpsertHooks, commentTenantConfigHook)
		commentTenantConfigAfterUpsertMu.Unlock()
	}
}

// OneG returns a single commentTenantConfig record from the query using the global executor.
func (q commentTenantConfigQuery) OneG() (*CommentTenantConfig, error) {
	return q.One(boil.GetDB())
}

// One returns a single commentTenantConfig record from the query.
func (q commentTenantConfigQuery) One(exec boil.Executor) (*CommentTenantConfig, error) {
	o := &CommentTenantConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for comment_tenant_configs")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all CommentTenantConfig records from the query using the global executor.
func (q commentTenantConfigQuery) AllG() (CommentTenantConfigSlice, error) {
	return q.All(boil.GetDB())
}

// All returns all CommentTenantConfig records from the query.
func (q commentTenantConfigQuery) All(exec boil.Executor) (CommentTenantConfigSlice, error) {
	var o []*CommentTenantConfig

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to CommentTenantConfig slice")
	}

	if len(commentTenantConfigAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all CommentTenantConfig records in the query using the global executor
func (q commentTenantConfigQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// Count returns the count of all CommentTenantConfig records in the query.
func (q commentTenantConfigQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count comment_tenant_configs rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q commentTenantConfigQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// Exists checks if the row exists in the table.
func (q commentTenantConfigQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if comment_tenant_configs exists")
	}

	return count > 0, nil
}

// Tenant pointed to by the foreign key.
func (o *CommentTenantConfig) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (commentTenantConfigL) LoadTenant(e boil.Executor, singular bool, maybeCommentTenantConfig interface{}, mods queries.Applicator) error {
	var slice []*CommentTenantConfig
	var object *CommentTenantConfig

	if singular {
		var ok bool
		object, ok = maybeCommentTenantConfig.(*CommentTenantConfig)
		if !ok {
			object = new(CommentTenantConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCommentTenantConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCommentTenantConfig))
			}
		}
	} else {
		s, ok := maybeCommentTenantConfig.(*[]*CommentTenantConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCommentTenantConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCommentTenantConfig))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &commentTenantConfigR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &commentTenantConfigR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.CommentTenantConfig = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.CommentTenantConfig = local
				break
			}
		}
	}

	return nil
}

// SetTenantG of the commentTenantConfig to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.CommentTenantConfig.
// Uses the global database handle.
func (o *CommentTenantConfig) SetTenantG(insert bool, related *Tenant) error {
	return o.SetTenant(boil.GetDB(), insert, related)
}

// SetTenant of the commentTenantConfig to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.CommentTenantConfig.
func (o *CommentTenantConfig) SetTenant(exec boil.Executor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"comment_tenant_configs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, commentTenantConfigPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.TenantID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &commentTenantConfigR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			CommentTenantConfig: o,
		}
	} else {
		related.R.CommentTenantConfig = o
	}

	return nil
}

// CommentTenantConfigs retrieves all the records using an executor.
func CommentTenantConfigs(mods ...qm.QueryMod) commentTenantConfigQuery {
	mods = append(mods, qm.From("\"comment_tenant_configs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"comment_tenant_configs\".*"})
	}

	return commentTenantConfigQuery{q}
}

// FindCommentTenantConfigG retrieves a single record by ID.
func FindCommentTenantConfigG(tenantID string, selectCols ...string) (*CommentTenantConfig, error) {
	return FindCommentTenantConfig(boil.GetDB(), tenantID, selectCols...)
}

// FindCommentTenantConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCommentTenantConfig(exec boil.Executor, tenantID string, selectCols ...string) (*CommentTenantConfig, error) {
	commentTenantConfigObj := &CommentTenantConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"comment_tenant_configs\" where \"tenant_id\"=$1", sel,
	)

	q := queries.Raw(query, tenantID)

	err := q.Bind(nil, exec, commentTenantConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from comment_tenant_configs")
	}

	if err = commentTenantConfigObj.doAfterSelectHooks(exec); err != nil {
		return commentTenantConfigObj, err
	}

	return commentTenantConfigObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *CommentTenantConfig) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CommentTenantConfig) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no comment_tenant_configs provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commentTenantConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	commentTenantConfigInsertCacheMut.RLock()
	cache, cached := commentTenantConfigInsertCache[key]
	commentTenantConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			commentTenantConfigAllColumns,
			commentTenantConfigColumnsWithDefault,
			commentTenantConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"comment_tenant_configs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"comment_tenant_configs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into comment_tenant_configs")
	}

	if !cached {
		commentTenantConfigInsertCacheMut.Lock()
		commentTenantConfigInsertCache[key] = cache
		commentTenantConfigInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single CommentTenantConfig record using the global executor.
// See Update for more documentation.
func (o *CommentTenantConfig) UpdateG(columns boil.Columns) (int64, error) {
	return o.Update(boil.GetDB(), columns)
}

// Update uses an executor to update the CommentTenantConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CommentTenantConfig) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	commentTenantConfigUpdateCacheMut.RLock()
	cache, cached := commentTenantConfigUpdateCache[key]
	commentTenantConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			commentTenantConfigAllColumns,
			commentTenantConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update comment_tenant_configs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"comment_tenant_configs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, commentTenantConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, append(wl, commentTenantConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update comment_tenant_configs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for comment_tenant_configs")
	}

	if !cached {
		commentTenantConfigUpdateCacheMut.Lock()
		commentTenantConfigUpdateCache[key] = cache
		commentTenantConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q commentTenantConfigQuery) UpdateAllG(cols M) (int64, error) {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q commentTenantConfigQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for comment_tenant_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for comment_tenant_configs")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o CommentTenantConfigSlice) UpdateAllG(cols M) (int64, error) {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CommentTenantConfigSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentTenantConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"comment_tenant_configs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, commentTenantConfigPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in commentTenantConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all commentTenantConfig")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *CommentTenantConfig) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CommentTenantConfig) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orm: no comment_tenant_configs provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commentTenantConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	commentTenantConfigUpsertCacheMut.RLock()
	cache, cached := commentTenantConfigUpsertCache[key]
	commentTenantConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			commentTenantConfigAllColumns,
			commentTenantConfigColumnsWithDefault,
			commentTenantConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			commentTenantConfigAllColumns,
			commentTenantConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert comment_tenant_configs, could not build update column list")
		}

		ret := strmangle.SetComplement(commentTenantConfigAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(commentTenantConfigPrimaryKeyColumns) == 0 {
				return errors.New("orm: unable to upsert comment_tenant_configs, could not build conflict column list")
			}

			conflict = make([]string, len(commentTenantConfigPrimaryKeyColumns))
			copy(conflict, commentTenantConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"comment_tenant_configs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(commentTenantConfigType, commentTenantConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert comment_tenant_configs")
	}

	if !cached {
		commentTenantConfigUpsertCacheMut.Lock()
		commentTenantConfigUpsertCache[key] = cache
		commentTenantConfigUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteG deletes a single CommentTenantConfig record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *CommentTenantConfig) DeleteG() (int64, error) {
	return o.Delete(boil.GetDB())
}

// Delete deletes a single CommentTenantConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CommentTenantConfig) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no CommentTenantConfig provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), commentTenantConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"comment_tenant_configs\" WHERE \"tenant_id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from comment_tenant_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for comment_tenant_configs")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q commentTenantConfigQuery) DeleteAllG() (int64, error) {
	return q.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all matching rows.
func (q commentTenantConfigQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no commentTenantConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from comment_tenant_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for comment_tenant_configs")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o CommentTenantConfigSlice) DeleteAllG() (int64, error) {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CommentTenantConfigSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(commentTenantConfigBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentTenantConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"comment_tenant_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commentTenantConfigPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from commentTenantConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for comment_tenant_configs")
	}

	if len(commentTenantConfigAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *CommentTenantConfig) ReloadG() error {
	if o == nil {
		return errors.New("orm: no CommentTenantConfig provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CommentTenantConfig) Reload(exec boil.Executor) error {
	ret, err := FindCommentTenantConfig(exec, o.TenantID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommentTenantConfigSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("orm: empty CommentTenantConfigSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommentTenantConfigSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CommentTenantConfigSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentTenantConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"comment_tenant_configs\".* FROM \"comment_tenant_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commentTenantConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in CommentTenantConfigSlice")
	}

	*o = slice

	return nil
}

// CommentTenantConfigExistsG checks if the CommentTenantConfig row exists.
func CommentTenantConfigExistsG(tenantID string) (bool, error) {
	return CommentTenantConfigExists(boil.GetDB(), tenantID)
}

// CommentTenantConfigExists checks if the CommentTenantConfig row exists.
func CommentTenantConfigExists(exec boil.Executor, tenantID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"comment_tenant_configs\" where \"tenant_id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, tenantID)
	}
	row := exec.QueryRow(sql, tenantID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if comment_tenant_configs exists")
	}

	return exists, nil
}

// Exists checks if the CommentTenantConfig row exists.
func (o *CommentTenantConfig) Exists(exec boil.Executor) (bool, error) {
	return CommentTenantConfigExists(exec, o.TenantID)
}
